In [2]:
import torch.nn as nn
import torch.nn.functional as F
import pandas as pd
import torch
import numpy as np
from torch.utils.data import Dataset, DataLoader
from torch import Tensor
from tqdm import tqdm
import math

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")

Using device: cpu


### Encoder-Decoder dataset

### Poetry dataset

In [3]:
df = pd.read_csv('/home/matta/repos/autumn_school/data/russianPoetryWithTheme.csv')

In [4]:
df = df[['author', 'text']]

In [5]:
df

,author,text
0,Михаил Лермонтов,"Забывши волнения жизни мятежной,\r\nОдин жил в..."
1,Сергей Есенин,"Нивы сжаты, рощи голы,\r\nОт воды туман и сыро..."
2,Игорь Северянин,Лючинь печальная читала вечером ручьисто-вкрад...
3,Анатолий Жигулин,"Глыбу кварца разбили молотом,\r\nИ, веселым ог..."
4,Николай Тихонов,"Хлынул дождь, когда девушки, встав в хоровод,\..."
...,...,...
16689,Леонид Мартынов,Седо\r\nКурчавятся облака\r\nНад чернотою поле...
16690,Гаврила Державин,"Белокурая Параша,\r\nСребророзова лицом,\r\nКо..."
16691,Федор Сологуб,"Сладкозвучная богиня,\r\nРифма золотая,\r\nСлу..."
16692,Илья Эренбург,Я так любил тебя — до грубых шуток\r\nИ до так...


In [6]:
alphabet = ''.join(chr(i) for i in range(ord('а'), ord('я') + 1))
alphabet += ' \n.,!?-«»()—…:;\"\''

In [7]:
df['text'] = df['text'].str.lower().apply(lambda x: '<start> ' + ''.join([ch for ch in x if ch in alphabet]) + ' <end>')

In [8]:
chars = sorted(set(list(''.join(df['text'].to_list()))))
vocab_size = len(chars)
stoi = {ch: i for i,ch in enumerate(chars)} # string to index
itos = {i: ch for i,ch in enumerate(chars)} # index to string
encode = lambda s: [stoi[c] for c in s]
decode = lambda l: ''.join([itos[i] for i in l])

### Transformer

In [9]:
class SelfAttention(nn.Module):
	"""
	Multiple heads of self-attention in parallel
	"""
	def __init__(self, emb_size, num_heads, head_size, dropout=0.0):
		super().__init__()
		self.head_size = head_size
		self.query = nn.Linear(emb_size, num_heads * head_size, bias=False)
		self.key = nn.Linear(emb_size, num_heads * head_size, bias=False)
		self.value = nn.Linear(emb_size, num_heads * head_size, bias=False)
		self.dropout = nn.Dropout(dropout)
		self.softmax = nn.Softmax(dim=-1)
		self.linear = nn.Linear(num_heads * head_size, emb_size)
		
	def forward(self, x):
		batch_size, seq_len, emb_size = x.shape
		Q = self.query(x).view(batch_size, seq_len, -1, self.head_size).transpose(1, 2)
		K = self.key(x).view(batch_size, seq_len, -1, self.head_size).transpose(1, 2)
		V = self.value(x).view(batch_size, seq_len, -1, self.head_size).transpose(1, 2)

		attention_score = Q @ K.transpose(-2, -1) / (self.head_size ** 0.5)

		mask = torch.tril(torch.ones(seq_len, seq_len)).to(x.device)
		attention_score = attention_score.masked_fill(mask == 0, float('-inf'))

		out = self.softmax(attention_score) @ V
		out = out.transpose(1, 2).reshape(batch_size, seq_len, -1)
		out = self.linear(out)
		out = self.dropout(out)

		return out

In [10]:
class FeedForwardNetwork(nn.Module):
	"""
	A simple linear layer followed by a non-linearity
	"""
	def __init__(self, emb_size, hidden_size, dropout=0.0):	
		super().__init__()
		self.linear1 = nn.Linear(emb_size, hidden_size)
		self.linear2 = nn.Linear(hidden_size, emb_size)
		self.relu = nn.ReLU()
		self.dropout = nn.Dropout(dropout)

	def forward(self, x):
		x = self.linear1(x)
		x = self.relu(x)
		x = self.dropout(x)
		x = self.linear2(x)
		return x

In [11]:
class TransformerBlock(nn.Module):
	"""
	Transformer block: communication followed by computation
	"""
	def __init__(self, emb_size, num_heads, head_size, hidden_size, post_ln=False, dropout=0.0):
		super().__init__()
		self.post_ln = post_ln
		self.attention = SelfAttention(emb_size, num_heads, head_size, dropout)
		self.ffn = FeedForwardNetwork(emb_size, hidden_size, dropout)
		self.norm1 = nn.LayerNorm(emb_size)
		self.norm2 = nn.LayerNorm(emb_size)
		
	def forward(self, x):
		if self.post_ln:
			x = self.norm1(x + self.attention(x))
			x = self.norm2(x + self.ffn(x))
		else:
			x = self.attention(self.norm1(x)) + x
			x = self.ffn(self.norm2(x)) + x
		return x

In [ ]:
class GPT(nn.Module):
	def __init__(self, dict_size, emb_size, seq_len, num_heads=8, head_size=64, hidden_size=2048, dropout=0.3):
		super().__init__()
		self.max_len = seq_len
		self.token_embedding_table = nn.Embedding(num_embeddings=dict_size, embedding_dim=emb_size)
		self.blocks = nn.Sequential(
			*[
				TransformerBlock(
				emb_size=emb_size,
		   		num_heads=num_heads,
				head_size=head_size,
				hidden_size=hidden_size,
				dropout=dropout
				) for _ in range(6)
			]
		)
		self.flatten = nn.Flatten()
		self.linear = nn.Linear(emb_size, dict_size)
		self.apply(self._init_weights)

	def _init_weights(self, module):
		if isinstance(module, nn.Linear):
			torch.nn.init.normal_(module.weight, mean=0.0, std=0.02)
			if module.bias is not None:
				torch.nn.init.zeros_(module.bias)
		elif isinstance(module, nn.Embedding):
			torch.nn.init.normal_(module.weight, mean=0.0, std=0.02)

	def forward(self, idx):
		emb = self.token_embedding_table(idx)
		out = self.blocks(emb)
		logits = self.linear(out)
		return logits

	@torch.no_grad()
	def generate(self, idx, num_tokens=1):
		for _ in range(num_tokens):
			idx_crop = idx if idx.shape[1] <= self.max_len else idx[:, -self.max_len:]

			logits = self.forward(idx_crop)[:, -1, :]
			probs = F.softmax(logits, dim=-1)

			id_next = torch.multinomial(probs, num_samples=1)
			idx = torch.cat((idx, id_next), dim=1)

		return idx

### Names dataset

In [13]:
f = open('./data/names.txt', 'r')
names = f.read().splitlines()

In [14]:
class NamesDataset(Dataset):
	def __init__(self, names: list[str], seq_len: int=3):
		self._seq_len = seq_len
		self.__stoi = {
			"<pad>": 0,
			"<start>": 1,
			"<end>": 2,	
		}

		for i, ch in enumerate(sorted(set(''.join(names)))):
			self.__stoi[ch] = i + 3
		self.__itos = {i: ch for ch, i in self.__stoi.items()}

		self.names: list[tuple[str, str]] = []
		self.names_encoded: list[tuple[Tensor, Tensor]] = []

		for name in names:
			tokens = [self.__stoi['<start>']] + [self.__stoi[ch] for ch in name] + [self.__stoi['<end>']]
			strs = ['<start>'] + list(name) + ['<end>']

			if len(tokens) < seq_len:
				tokens = tokens + [self.__stoi['<pad>']] * (seq_len - len(tokens))
				strs = strs + ['<pad>'] * (seq_len - len(strs))
			elif len(tokens) > seq_len:
				tokens = tokens[:seq_len]
				strs = strs[:seq_len]

			input_seq = torch.tensor(tokens[:-1])
			target_seq = torch.tensor(tokens[1:])

			self.names.append((''.join(strs[:-1]), ''.join(strs[1:])))
			self.names_encoded.append((input_seq, target_seq))

	def __len__(self):
		return len(self.names_encoded)
	
	@property
	def seq_len(self):
		return self._seq_len
	
	@property
	def stoi(self):
		return self.__stoi
	
	@property	
	def itos(self):
		return self.__itos
	
	def get_sample(self, idx):
		return self.names[idx]
	
	def __getitem__(self, idx):
		return self.names_encoded[idx]

In [15]:
names_dataset = NamesDataset(names, seq_len=8)
names_loader = DataLoader(names_dataset, batch_size=32, shuffle=True)

In [16]:
for i in range(5):
	print(names_dataset.get_sample(i))

('<start>emma<end><pad>', 'emma<end><pad><pad>')
('<start>olivia', 'olivia<end>')
('<start>ava<end><pad><pad>', 'ava<end><pad><pad><pad>')
('<start>isabel', 'isabell')
('<start>sophia', 'sophia<end>')


In [17]:
model = GPT(
	dict_size=len(names_dataset.stoi),
	emb_size=8, seq_len=names_dataset.seq_len,
	hidden_size=64, num_heads=8,
	head_size=64,
	dropout=0.3).to(device)

In [18]:
optim = torch.optim.AdamW(model.parameters(), lr=3e-4)
criterion = nn.CrossEntropyLoss(ignore_index=names_dataset.stoi["<pad>"])

In [19]:
epochs = 5
loss_history = []
perplexity_history = []

In [21]:
for epoch in range(epochs):
	model.train()
	total_loss = 0
	for input, target in tqdm(names_loader):
		input, target = input.to(device), target.to(device)
		optim.zero_grad()
		logits = model(input)
		loss = criterion(
			logits.view(-1, logits.size(-1)),
			target.view(-1)
		)
		loss.backward()
		optim.step()
		total_loss += loss.item()

	avg_loss = total_loss / len(names_loader)
	perplexity = math.exp(avg_loss)
	loss_history.append(avg_loss)
	perplexity_history.append(perplexity)
	print(f"Epoch {epoch + 1} / {epochs}, Loss: {avg_loss:.4f}, Perplexity: {perplexity:.4f}")

100%|██████████| 1002/1002 [00:58<00:00, 16.99it/s]


Epoch 1 / 5, Loss: 2.6702, Perplexity: 14.4423


100%|██████████| 1002/1002 [00:40<00:00, 24.75it/s]


Epoch 2 / 5, Loss: 2.5491, Perplexity: 12.7953


100%|██████████| 1002/1002 [00:18<00:00, 54.19it/s]


Epoch 3 / 5, Loss: 2.5249, Perplexity: 12.4892


100%|██████████| 1002/1002 [00:18<00:00, 55.02it/s]


Epoch 4 / 5, Loss: 2.5084, Perplexity: 12.2855


100%|██████████| 1002/1002 [00:16<00:00, 60.06it/s]

Epoch 5 / 5, Loss: 2.4920, Perplexity: 12.0859


In [ ]:
torch.save(model.state_dict(), '/kaggle/working/gpt-name-3')

In [ ]:
state_dict = torch.load('./weights/gpt-name-3', weights_only=True, map_location=device)
model.load_state_dict(state_dict)

<All keys matched successfully>

In [22]:
def generate_name(model):
	model.eval()
	itos = names_dataset.itos
	start_token = names_dataset.stoi['<start>']
	end_token = names_dataset.stoi['<end>']
	pad_token = names_dataset.stoi['<pad>']
	idx = torch.tensor([[start_token]], device=device)
	inference = model.generate(idx, num_tokens=names_dataset.seq_len)
	print(inference)
	tokens = inference[0].tolist()

	name = []
	for token in tokens[1:]:
		if token == end_token:
			break
		name.append(itos[token])
	return ''.join(name)

In [29]:
for _ in range(10):
	print(generate_name(model))

tensor([[ 1,  7, 14,  3, 24,  2,  7, 10,  2]])
elav
tensor([[ 1, 20,  3, 20,  3, 14,  7, 20,  2]])
raraler
tensor([[ 1,  3, 21, 27, 16, 22, 21, 10, 17]])
asyntsho
tensor([[ 1,  4,  7, 20,  5,  7,  7,  2,  7]])
bercee
tensor([[ 1, 21,  3, 11,  6,  7, 16, 11,  2]])
saideni
tensor([[ 1, 21, 10,  7, 22,  3, 16,  2,  7]])
shetan
tensor([[ 1, 16, 11, 17,  6, 27, 10,  2, 17]])
niodyh
tensor([[ 1,  5, 17, 20,  3, 15, 20, 11, 16]])
coramrin
tensor([[ 1, 15,  3, 20, 16,  3,  2,  2,  7]])
marna
tensor([[ 1, 13,  3,  7, 16, 10, 14,  2,  2]])
kaenhl
